---
layout: tutorial
label: Points
title: Points
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width = 14)
knitr::opts_chunk$set(fig.height = 14)
set.seed(1234)
```

## Plotting Points

To plot points in a karyoplot we need to use the `kpPoints` function. Given a
character vector _chr_ and two integer vectors _x_ and _y_ it will plot points 
in the specifid positions. 


```{r Figure1, message=FALSE, warning=FALSE, fig.height=5}

library(karyoploteR)

x <- 1:23*10e6
y <- rnorm(23, mean=0.5, sd=0.25)

kp <- plotKaryotype(chromosomes="chr1")
kpPoints(kp, chr="chr1", x=x, y=y)

```


The glyphs used to represent the points can be customized with the same 
graphical parameters as in the R base graphics `points` function: pch, cex, col...

```{r Figure2, message=FALSE, warning=FALSE, fig.height=5}
kp <- plotKaryotype(chromosomes="chr1")
kpPoints(kp, chr="chr1", x=x, y=y)
kpPoints(kp, chr="chr1", x=x, y=y, pch=1, cex=2, col="red")
kpPoints(kp, chr="chr1", x=x, y=y+0.15, cex=2, pch=1:23, col="blue")
kpPoints(kp, chr="chr1", x=x, y=y+0.3, cex=(1:23)/5, col=rainbow(23))

```





